name=datatables-select
repo=DataTables/Select
license.name=MIT
license.url=https://github.com/DataTables/Select/blob/master/License.txt
download=https://datatables.net/releases/Select-${version}.zip
requirejs.main=datatables-select
base.dir=*/
