name=datatables-buttons
repo=DataTables/Buttons
license.name=MIT
license.url=https://github.com/DataTables/Buttons/blob/master/License.txt
download=https://datatables.net/releases/Buttons-${version}.zip
requirejs.main=datatables-buttons
base.dir=*/
