name=Leaflet
repo=Leaflet/Leaflet
download=https://github.com/Leaflet/Leaflet/releases/download/v${version}/leaflet.zip
base.dir=dist
requirejs.main=leaflet
license.name=BSD-2-Clause
license.url=https://github.com/Leaflet/Leaflet/blob/main/LICENSE
